### ISSUE TITLE
Add a Cron job to run scans

### ISSUE THREAD

**Issue by jithindasad** [code-mancers/gitlab-dependabot-example#26]

**Comment by jithindasad** [comment]
`Heroku scheduler` needs the free tier account to be verified, Tried to work around this problem with other services like Redis However It also required another addon called `RedisToGo`. 

setting up a  cron job manually on Heroku is not possible this is partly due to due to Heroku’s Dyno infrastructure, which is composed of virtualized Linux containers that are restarted daily, which resets it’s file system. Heroku also states that Cron does not perform well on horizontally scaling platforms.

@thegeorgeous

**Comment by thegeorgeous** [comment]
@jithindasad will close this issue for now then.
