### ISSUE TITLE
[Bug] Error in Heroku Production

### ISSUE THREAD

**Issue by jithindasad** [code-mancers/gitlab-dependabot-example#28]
Heroku logs

ActionView::Template::Error (PG::UndefinedTable: ERROR:  relation "repositories" does not exist

**Comment by jithindasad** [comment]
Fixed! Migration was not run on production
`heroku run rake db:migrate` fixed it.

https://gitlab-dependabot-example.herokuapp.com/

**Comment by thegeorgeous** [comment]
@jithindasad why does `db:migrate` not run automatically during deploys?

**Comment by sreecodeslayer** [comment]
> @jithindasad why does `db:migrate` not run automatically during deploys?

Folks, I think a procfile with

```
web: bundle exec ...
release: rake db:migrate
```
is needed?

More [here](https://devcenter.heroku.com/articles/release-phase)

**Comment by thegeorgeous** [comment]
@sreecodeslayer nice catch. I'm surprised Heroku accepted without a Procfile!

**Comment by sreecodeslayer** [comment]
> @sreecodeslayer nice catch. I'm surprised Heroku accepted without a Procfile!

Apparently they support repos without a procfile by guessing the app and runnning basic commands themselves, in case of rails its,
precompile assets and run the webrick server i suppose

They put a warning in build logs saying:
```
###### WARNING:

       No Procfile detected, using the default web server.

       We recommend explicitly declaring how to boot your server process via a Procfile.

       https://devcenter.heroku.com/articles/ruby-default-web-server
```

**Comment by jithindasad** [comment]
@sreecodeslayer My bad, I thought Heroku pipeline automatically does that(running migrations). Thank you! 

Instead of `rake db:migrate` I have put `rails db:prepare` in my Procfile. Thought It will be a better option. 

[more](https://blog.saeloun.com/2019/04/11/rails-6-rails-db-prepare.html)
